kordat <- read.table(file="variants20.txt", header=TRUE, row.names=1, dec=",", strip.white=TRUE, sep="\t")
kordat[9:ncol(kordat)] <- lapply(kordat[9:ncol(kordat)], as.factor)
sink("results.txt")
cat("Faktoru kopsavilkums:\n")
print(summary(kordat[,9:ncol(kordat)]))
sink()
sl.by.b <- split(kordat$Slope, kordat$b)
sink("results.txt", append=TRUE)
cat("Liste no Slope un b:\n")
print(sl.by.b)
kordat$Average <- apply(kordat[,c("Slope", "Intercept", "adj.r.squared")], 1, mean)
cat("Jauna kolnna Average:\n")
print(kordat$Average)
std <- tapply(kordat$Average ,kordat$f, sd)
cat("Standartnovirze:\n")
print(std)
prockordat <- kordat[kordat$adj.r.squared > 0.7, ]
invert_slope <- function(x) { 1 - 1 / x }
prockordat$Slope <- invert_slope(prockordat$Slope)
cat("\nProckordat datu satvars:\n")
print(prockordat)
sink()
svg("scatter.svg")
plot(kordat$MAD,kordat$Average,xlab="MAD",ylab="Average",main="MAD un Average",pch=16,col="blue")
dev.off()
svg("boxplot.svg")
boxplot(split(kordat$Intercept, kordat$f), col = rainbow(length(unique(kordat$f))), outpch = 16,
        main = "Intercept Boxplot pēc f faktora līmeņiem", xlab = "f Faktora līmeņi", ylab = "Intercept vērtības")
dev.off()
limenu_skaits <- table(unlist(strsplit(rownames(kordat), "\\.")))
max_limenis <- names(which.max(limenu_skaits))
jaunais_prockordat <- prockordat[grepl(max_limenis, rownames(prockordat)), ]
cat("\nRindas ar visbiežāk sastopamo faktora līmeni (", max_limenis, "):\n")
print(jaunais_prockordat)